Resolve WASM runtime failure "Cannot enlarge memory arrays"
 - WASM module was failing during runtime with this error because
   marian enlarges the memory workspace

 - Added compilation flag: "-s ALLOW_MEMORY_GROWTH=1"

 - Adding this flag causes compilation error:
    "USE_PTHREADS + ALLOW_MEMORY_GROWTH may run non-wasm code slowly"
  -- Converted this error to a warning